version: "3.9"
services:
  credit_forecast:
    build: .
    image: credit_forecast:local
    env_file: [.env.docker]
    ports: ["8080:8080", "8081:8081", "8082:8082"]
    depends_on: [postgres]
  postgres:
    image: "postgres:14.2"
    restart: always
    env_file: ["postgres/.env.docker"]
    ports: ["5432:5432"]
    volumes: ["./postgres/data:/var/lib/mysql"]
